### ISSUE TITLE
rName not being set properly for pie chart (i.e. when dynamicColumnWidth used)

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#458]
For pie charts the `dynamicColumnWidth` property is used instead of `rAccessor`. Would this have something to do with `rName` not being set properly?

I'm just seeing the value `function-0` for `rName`.

![rname-property-missing](https://user-images.githubusercontent.com/1482075/55739822-c2322e80-5a21-11e9-902b-938c82373c34.png)

**Comment by emeeks** [comment]
rName only refers to the rAccessor so since you're sending a function (presumably `() => 1`) it's just telling you that there's a function for the `r` and it doesn't know what that is. `dynamicColumnWidth` doesn't support arrays (yet) and so you should be able to pass whatever variable you have for that to your tooltip generator.

**Comment by dgwyer** [comment]
I'm not sure I follow. Could you show me an example of how I'd pass the value of the data series to the tooltip generator? i.e. without hard coding it.

I'm not seeing the value of `dynamicColumnWidth` anywhere in the data inside the tooltip. Or are you saying this string isn't available yet and has to be hard coded?

**Comment by emeeks** [comment]
Sorry I didn't realize I'd left this off for 11 days. What I mean is that you should know the value for your dynamicColumnWidth because you're passing it to the frame, so you could pass the same value to your `tooltipContent` function in order to access that value on hover. That said, I think it does make sense (for pie charts) to allow arrays into `dynamicColumnWidth` and so you should expect feature parity on that part with `rAccessor`.

**Comment by emeeks** [comment]
In 2.0 pieces will be decorated with a `wName` that corresponds to `dynamicColumnWidth` and it will accept arrays.

**Comment by emeeks** [comment]
Actually, now that I've looked at this more closely, `dynamicColumnWidth` is a column property, and not a piece property, and so it doesn't make sense to allow it to take arrays, since that inflates pieces but does not inflate columns.
