### ISSUE TITLE
Radial chart variable column heights depend on the data entry field name

### ISSUE THREAD

**Issue by artemverbo** [nteract/semiotic#462]
Hi!

I'm having a bit of an odd issue with radial charts column `heights`, not `widths`.

1) When my data entries have an `r` field called `value` and I set `dynamicColumnWidth: 'value'` (or via function, doesn't matter), I get elements rendered with variable heights like so:
![Screen Shot on 2019-04-17 at 13-08-16](https://user-images.githubusercontent.com/1530975/56253887-7a429400-6112-11e9-9caf-9946de7e2ddb.png)

2) As soon as I rename the data field to anything other than `value`, say to `v` and use `dynamicColumnWidth: 'v'`, it seems to behave as expected:
![Screen Shot on 2019-04-17 at 13-09-57](https://user-images.githubusercontent.com/1530975/56253908-947c7200-6112-11e9-925d-3e006f0d397d.png)

Is that a bug or kind of an undocumented feature? :)

Thanks!

**Comment by emeeks** [comment]
This is a bug that probably won't be fixed until 2.0 based on how the individual pieces are being decorated. The generated datapoint is an object with a `data` prop that corresponds to the original datapoint and a `value` prop that encodes the value (based on your accessor) onto the generated object. Earlier on I used JS symbols to avoid these kinds of collisions but they proved messy and difficult to then translate them back to the user.

The reason I probably won't fix this before 2.0 is because it only happens in these corner cases and also I can't change the generated object spec, which gets exposed in some places, without a major version change.
