### ISSUE TITLE
Different tooltip behavior observed for bar chart with flattened vs. non flattened data

### ISSUE THREAD

**Issue by dgwyer** [nteract/semiotic#463]
For non-flattened data, the tooltip shows the data for all pieces on a stacked bar chart whereas when using flattened data the tooltip shows the data for each individual piece.

You can see this behavior here: https://codepen.io/dgwyer/pen/wZymaQ

Would it be possible to make the tooltips have consistent behavior? Or is it possible to get the same behavior for non-flattened data with a custom tooltip?

**Comment by emeeks** [comment]
Thanks for catching this, I'll get it fixed. You should not get different behavior in these two cases.

**Comment by emeeks** [comment]
Oh looking at it I thought you were reporting a different bug which is that the tooltip location seems to be different. I can't emit the same data in the two different cases because underneath the data is different. The piece hover only knows the data for the piece it's hovering over and wouldn't be able to tell you otherwise. However, you could use the column hover (`hoverAnnotation`) which has info for all of the pieces, along with a custom tooltip that accounts for the difference in structure, such as this:
https://codepen.io/emeeks/pen/KYRjZJ

I will also make sure to fix the difference in the position of the tooltip.

**Comment by dgwyer** [comment]
I understand. Just wanted to flag this in case it wasn't the expected behavior.

And using the new `rName` property we can easily replicate the flattened data tooltip behavior using a custom solution.

https://codepen.io/dgwyer/pen/wZymaQ
